FROM ai-copilot.tencentcloudcr.com/ai-copilot/keycloak:e8799eb8a9a29961602b37c7723f067983188933-arm

COPY providers/keycloak-copilot-provider-custom.jar /opt/keycloak/providers/keycloak-copilot-provider-custom.jar

