FROM show-how-docker.pkg.coding.net/huanghenongshang/bookinfo/keycloak:2025.04.22-arm64-277707126815f84f1058a08518d94398d2e00674

COPY providers/keycloak-copilot-provider-custom.jar /opt/keycloak/providers/keycloak-copilot-provider-custom.jar

