name: Build keycloak ARM64 Images

# on:
#   push:
#     branches: [main]
#   workflow_dispatch:

# 手动执行
on:
  workflow_dispatch:

jobs:
  build-arm64-docker:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git credentials
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}

      - name: Create providers directory
        run: mkdir -p arm/providers

      - name: Download .jar file
        run: |
          curl -L -o arm/providers/keycloak-copilot-provider-custom.jar https://temp-1252238228.cos.ap-beijing.myqcloud.com/build/keycloak-copilot-provider-custom.jar

      - name: Set up QEMU (for ARM64 emulation)
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to registry-c.cmft.com
        uses: docker/login-action@v3
        with:
          registry: registry-c.cmft.com
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set image tag variables
        id: set_image_tag
        run: |
          DATE=$(date +'%Y.%m.%d')
          # GIT_SHA=$(git rev-parse --short=40 HEAD)
          GIT_SHA=277707126815f84f1058a08518d94398d2e00674
          TAG="registry-c.cmft.com/cmhk-code-asst-di/keycloak:${DATE}-arm64-${GIT_SHA}-custom-sso"
          echo "tag=${TAG}" >> $GITHUB_OUTPUT

      - name: Build and push ARM64 Docker image
        uses: docker/build-push-action@v5
        with:
          context: arm
          file: arm/Dockerfile
          push: true
          tags: ${{ steps.set_image_tag.outputs.tag }}
          platforms: linux/arm64
          provenance: false # 可选：关闭 SBOM 生成，加快构建

      - name: Write tag to arm/tag_version.txt
        run: |
          echo "${{ steps.set_image_tag.outputs.tag }}" >> arm/tag_version.txt

      - name: Commit and push tag_version.txt to Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@github.com"

          git pull origin main
          git add arm/tag_version.txt

          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update ARM image tag on $(date '+%Y-%m-%d %H:%M:%S')"
            git push origin main
          fi
